"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 27;
let altura = 1.74;
const nacionalidade = "brasileira";
const colegas = ["João", "Maria", "José"];
const tecnologias = ["JavaScript", "TypeScript", "NodeJS"];
const notas = [10, 9, 8, 7, 6];
const lista = ["Jeb", true, 27];
let idadeDeAna = 25;
idadeDeAna = "25 anos";
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
let curso = 'Front-end';
